### ISSUE TITLE
Make a `POST` request instead of a `GET` request

### ISSUE THREAD

**Issue by WesCossick** [sparksuite/w3c-css-validator#115]
It turns out that it's possible to communicate with the W3C CSS Validator service via `POST` requests, by posting a form data encoded body. I'm not sure if this is something we missed when we first built this package, or if this is a new feature. It's how the [online tool](https://jigsaw.w3.org/css-validator/#validate_by_input) communicates with the validator. Here's a demonstration using Postman:

```json
{
	"info": {
		"_postman_id": "e5885319-e22e-4770-bedb-a95495aae38e",
		"name": "W3C CSS Validator",
		"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
	},
	"item": [
		{
			"name": "Test making a POST request",
			"request": {
				"method": "POST",
				"header": [],
				"body": {
					"mode": "formdata",
					"formdata": [
						{
							"key": "text",
							"value": ".test {}",
							"type": "default"
						},
						{
							"key": "usermedium",
							"value": "all",
							"type": "default"
						},
						{
							"key": "warning",
							"value": "no",
							"type": "default"
						},
						{
							"key": "output",
							"value": "application/json",
							"type": "default"
						},
						{
							"key": "profile",
							"value": "css3",
							"type": "default"
						}
					]
				},
				"url": {
					"raw": "https://jigsaw.w3.org/css-validator/validator",
					"protocol": "https",
					"host": [
						"jigsaw",
						"w3",
						"org"
					],
					"path": [
						"css-validator",
						"validator"
					]
				}
			},
			"response": []
		}
	]
}
```

Doing a `POST` request would avoid issues with the length of the CSS text causing the network request to fail, since we don't have to try to fit the CSS text into the URL.

**Comment by WesCossick** [comment]
Making this change would also allow use to eliminate these two blocks of code: 

- https://github.com/sparksuite/w3c-css-validator/blob/3293478549a467a3e5c401e56c974f34e8390aab/src/retrieve-validation/browser.ts#L29-L31
- https://github.com/sparksuite/w3c-css-validator/blob/3293478549a467a3e5c401e56c974f34e8390aab/src/retrieve-validation/node.ts#L19-L23

**Comment by corymharper** [comment]
We didn't miss it, but rather none of the available API documentation mentions a `POST` request, see https://jigsaw.w3.org/css-validator/manual.html#api and https://jigsaw.w3.org/css-validator/api.html, the second link mentions a `GET` request, so thats what the original design was based on.
