### ISSUE TITLE
Initial implementation

### ISSUE THREAD

**Issue by WesCossick** [sparksuite/w3c-css-validator#13]
### Intro

We'll use this issue, and its corresponding PR, to discuss the initial design and then implement it.

For reference, [this page](https://jigsaw.w3.org/css-validator/manual.html) explains how to call the service (see "Validation Request Format" section), while [this page](https://jigsaw.w3.org/css-validator/api.html) explains the response.

I'd like for this package to be cross-platform; meaning, it can be run in either a browser or Node.js environment. We _could_ use a package like `axios` to make this easy, but that adds an extra dependency when it's possibly unneeded. Instead, we could intelligently use either `fetch` (browser) or `http` (Node.js).

### Using this package

I propose the ability to use the package like so:

**Importing/requiring:**

```ts
// Modern
import cssValidator from 'w3c-css-validator';

// Legacy
var cssValidator = require('w3c-css-validator');
```

**Validating:**

```ts
// For validating CSS directly
const validationResult = await cssValidator.validateText('body { color: #000; }', {
    // Options go here
});

// In the future, we could support...
const validationResult = await cssValidator.validateURL('https://www.google.com/', {
    // Options go here
});
```

**Options:**

Key | Possible values | Default | Notes
--- | --- | --- | ---
`medium` | [See "7.3 Recognized media types"](https://www.w3.org/TR/CSS2/media.html) | `all` | Corresponds to the `usermedium` parameter
`warningLevel` | `0`, `1`, `2`, `3` | `0` | Corresponds to the `warning` parameter, with `0` = `no`, `1` = `0`, `2` = `1`, `3` = `2`

**Output:**

The output, or result, would be describe by this interface:

```ts
interface TextValidationResult {
    /** Whether the CSS is valid */
    valid: boolean;

    /** An array of errors found with the CSS; if none, this will be empty */
    errors: {
        line: number;
        message: string;
    }[];

    /** An array of warnings found with the CSS; if none, this will be empty */
    warnings: {
        line: number;
        level: 1 | 2 | 3;
        message: string;
    }[];
}
```

**Comment by WesCossick** [comment]
If `warningLevel` is missing or set to `0`, then the `warnings` array in the result should not be present at all.

**Comment by WesCossick** [comment]
W3C's service returns a lot of extra, undocumented information about errors and warnings. Especially errors. I searched through their public documentation, including their GitHub repo, and couldn't figure out all the possible values or what they mean. For that reason, I propose excluding the extra info for now, until we can understand it better.

For reference, here are some errors from validating Amazon's homepage, converted to JSON:

```json
{
    "line": "3",
    "errortype": "parse-error",
    "context": "#nav-logo .nav-logo-locale",
    "errorsubtype": "exp",
    "skippedstring": "regular",
    "type": "value",
    "message": "Value Error :  font-weight (nullfonts.html#propdef-font-weight)\n        \n                                “regular” is not a “font-weight” value :"
 },
 {
    "line": "3",
    "errortype": "parse-error",
    "context": "#nav-search",
    "errorsubtype": "skippedString",
    "skippedstring": "0\\9",
    "type": "generator.unrecognize",
    "message": "Unknown dimension"
 },
```

And here are some warnings:

```json
{
    "line": "1",
    "level": "0",
    "message": "“-moz-box” is an unknown vendor extension",
    "type": "vendor-extension"
 },
 {
    "line": "1",
    "level": "0",
    "message": "“-webkit-flex” is an unknown vendor extension",
    "type": "vendor-extension"
 },
```

**Comment by WesCossick** [comment]
I also propose holding off on creating the `validateURL()` function, but we should design the code with the ability to create this down the road. We'd need to introduce a different result interface, called `URLValidationResult`, which would group errors and warnings by their URLs.

**Comment by corymharper** [comment]
These proposals sound pretty good to me, if I understand what our minimum requirements for the package are, it'd look something like the following:

- cssValidator.validateText
- - Accepts a string, which should be the CSS to be validated
- - Accepts an options object as it's second parameter, taking the shape of
```
interface Options {
  medium?: string;
  warningLevel?: 0 | 1 | 2 | 3;
}
```
- - Outputs a return value that varies based on the options passed as indicated in the initial post
- Works without much if any variability between headless and browser based environments

**Comment by WesCossick** [comment]
That's pretty much exact. The only thing is that `medium` is a finite list, not just any `string`.
