### ISSUE TITLE
Demo website crashes on load

### ISSUE THREAD

**Issue by corymharper** [sparksuite/w3c-css-validator#130]
It appears that at some point, the demo website has been broken. If you try to load it currently, and look in the console, you'll see the following error:

```
Uncaught (in promise) ReferenceError: exports is not defined
    at 160 (4f320539.88b93df7.js:1:2372)
    at f (runtime~main.9d4915b1.js:1:970)
    at 159 (4f320539.88b93df7.js:1:1860)
    at f (runtime~main.9d4915b1.js:1:970)
    at 81 (4f320539.88b93df7.js:1:10897)
    at f (runtime~main.9d4915b1.js:1:970)
```

As far as I can tell currently, this has something to do with how we output the build using a CommonJS module. However, we successfully use this exact configuration in other projects without issue on our demo websites...

**Comment by corymharper** [comment]
If you look in the build at `dist/validate-text.js` you'll see this line: `exports.default = validateText;` which I think is the initial line the error throws on.

**Comment by WesCossick** [comment]
Running `yarn upgrade` in the `website/` directory seems to fix the issue. I assume one of the packages simply had a bug in it, but I'm not sure which one. I'll open a PR with the changes.
