### ISSUE TITLE
Hovering over "Get started" button hides text

### ISSUE THREAD

**Issue by WesCossick** [sparksuite/w3c-css-validator#145]
When hovering over the "Get started" button, the text disappears:

![GIF Recording 2022-12-16 at 4 49 58 PM](https://user-images.githubusercontent.com/3850064/208201568-a98fe3c9-9f1f-4419-86e5-d5a98c34f77e.gif)

**Comment by Nam-Nguyen-Dev** [comment]
Hey @WesCossick, I was thinking of styling the button like this on hover:

![W3C CSS Validator](https://user-images.githubusercontent.com/116038525/209013501-4c8ec9f1-d173-4d1a-86a2-22cb9991edb5.gif)

Please let me know your thoughts or suggestions! Thank you.

**Comment by corymharper** [comment]
> Hey @WesCossick, I was thinking of styling the button like this on hover:
> 
> ![W3C CSS Validator](https://user-images.githubusercontent.com/116038525/209013501-4c8ec9f1-d173-4d1a-86a2-22cb9991edb5.gif) [ ![W3C CSS Validator](https://user-images.githubusercontent.com/116038525/209013501-4c8ec9f1-d173-4d1a-86a2-22cb9991edb5.gif) ](https://user-images.githubusercontent.com/116038525/209013501-4c8ec9f1-d173-4d1a-86a2-22cb9991edb5.gif) [ ](https://user-images.githubusercontent.com/116038525/209013501-4c8ec9f1-d173-4d1a-86a2-22cb9991edb5.gif)
> 
> Please let me know your thoughts or suggestions! Thank you.

Hey @Nam-Nguyen-Dev, that's not a bad idea, definitely better than the current behavior. However, based on the currently implemented custom styles for that button, it seems to me like the intention for this button was for the font color to not change at all on hover. The primary issue here is that [Infimia](https://infima.dev/), the styling framework used by Docusarus has rules that are overriding our custom styles in an undesirable way. With that in mind, I'm going to open a pull request that prevents the problematic rules from overriding our styles.
