### ISSUE TITLE
CSS `validator` endpoint is down

### ISSUE THREAD

**Issue by tomstumshais** [sparksuite/w3c-css-validator#157]
Hey!

Nothing much to add, looks like server is down. Not working if you are checking your [Demo](https://sparksuite.github.io/w3c-css-validator/demo/) page or if you are using it as package.

Thanks.

**Comment by WesCossick** [comment]
The validator is run by the [World Wide Web Consortium](https://www.w3.org/); we've just built a package that communicates with their service.
