### ISSUE TITLE
Can't bundle with esbuild

### ISSUE THREAD

**Issue by DEfusion** [sparksuite/w3c-css-validator#175]
We're moving our project from webpack to esbuild and it fails with the following:

```
✘ [ERROR] Could not resolve "https"

    node_modules/w3c-css-validator/dist/retrieve-validation/node.js:10:23:
      10 │ import * as https from 'https';
         ╵                        ~~~~~~~

  The package "https" wasn't found on the file system but is built into node. Are you trying to
  bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

✘ [ERROR] Could not resolve "util"

    node_modules/w3c-css-validator/dist/retrieve-validation/node.js:13:28:
      13 │ import { TextEncoder } from 'util';
```

I tried adding the following to the `package.json` (both package and our project) and building it but that didn't work:

```
	"browser": {
		"https": "https-browserify",
		"util": "node-util"
	},
```

For now I've forked and have changed to only import `retrieve-validation/browser`, I was wondering if I should submit a PR to build 2 different versions with one explicitly for the browser?

**Comment by corymharper** [comment]
Check out the `resolve` property in our test project for the browser, https://github.com/sparksuite/w3c-css-validator/blob/master/test-projects/browser/webpack.config.js#L14, I'm not familiar with esbuild, but is there a similar configuration you can use?

**Comment by corymharper** [comment]
If you look at the code that actually calls those functions, https://github.com/sparksuite/w3c-css-validator/blob/master/src/retrieve-validation/index.ts#L42-L48, you'll see that in a browser there is no danger of actually calling the function that uses the `https` package.
