### ISSUE TITLE
Remove extraneous characters from error messages

### ISSUE THREAD

**Issue by corymharper** [sparksuite/w3c-css-validator#40]
The W3C validator API seems to treat error messages a little specifically for their use of it at https://jigsaw.w3.org/css-validator/#validate_by_input, and adds extra characters to the error message, typically including ` :`. We want our error messages to exist in various implementations, so these characters should be shaved off.

**Comment by WesCossick** [comment]
Here's an example, where there's a trailing ` :` which they use for their UI version:

![image](https://user-images.githubusercontent.com/3850064/109232753-6b0ce280-778e-11eb-8751-ee852bc5a5b0.png)
