### ISSUE TITLE
Errors received from https://jigsaw.w3.org/css-validator/validator with none json content throw an uncaught excaption

### ISSUE THREAD

**Issue by ShaulTransmit** [sparksuite/w3c-css-validator#93]
if https://jigsaw.w3.org/css-validator/validator returns anything that is not a json the following throws an uncaught exception:
`resolve(JSON.parse(data).cssvalidation);`
this cannot be caught by the application since it's done inside the `https.get... on('end'...)` callback.

The easiest way I found to reproduce this is to change the requested output to `application/xml`, but you can also probably set local routing for `jigsaw.w3.org` and serve some XML file from it

**Comment by WesCossick** [comment]
Fixed in [v1.2.0](https://github.com/sparksuite/w3c-css-validator/releases/tag/v1.2.0) via #94.
