### ISSUE TITLE
Fails with large files

### ISSUE THREAD

**Issue by heyimalex** [sparksuite/w3c-css-validator#98]
Not sure if this is a known issue, but thought I'd point it out. Because the text is passed through the query string, there's an upper bound on what you can validate, and I was running into it on some compiled stylesheets. Error would sometimes be a 400 bad request, sometimes an uncaught pipe error.

I got around this by just interacting with the webpage and parsing the html. It's brittle, and I only wanted errors, but could be a good starting point if anyone else needs to do this.

```js
// yarn add form-data node-fetch node-html-parser

async function validate(source) {
  // Reversed from interacting with https://jigsaw.w3.org/css-validator/#validate_by_input
  const form = new FormData();
  form.append("text", source);
  form.append("profile", "css3svg");
  form.append("usermedium", "all");
  form.append("type", "none");
  form.append("warning", "0");
  form.append("vextwarning", "");
  form.append("lang", "en");

  return fetch("https://jigsaw.w3.org/css-validator/validator", {
    headers: form.getHeaders(),
    body: form.getBuffer(),
    method: "POST",
  })
    .then((response) => {
      if (response.status !== 200) {
        throw new Error(`returned status code ${response.status}`);
      }
      return response.text();
    })
    .then((body) => {
      const root = HTMLParser.parse(body);
      const errors = root.querySelectorAll("tr.error").map((row) => {
        const line = parseInt(row.querySelector(".linenumber").text, 10);
        const error = row
          .querySelector(".parse-error")
          .text.replace(/\s+/g, " ")
          .trim();
        return { line, error };
      });
      return errors;
    });
}

**Comment by corymharper** [comment]
@heyimalex thanks for the report, we should be handling this error more gracefully. Another solution that may or may not be feasible for your use-case is utilizing `validateByURL` to pass the CSS file directly if you have a public remote access point for the file, or can create one temporarily.

**Comment by corymharper** [comment]
@WesCossick it doesn’t seem like there is any kind of industry standard limit on query strings, but that the bottleneck might be the specific server configuration they’re using… [This thread](https://stackoverflow.com/questions/812925/what-is-the-maximum-possible-length-of-a-query-string#:~:text=Although%20officially%20there%20is%20no,a%20max%20of%202048%20characters.) says that a pretty common limit is 1024 for query strings and that the entire URL is often limited to 2048, a security measure to prevent slow HTTP request DDOS attacks... Should we proceed by just following those guidelines? The only alternative would be purposely sending requests with too large queries and URL's directly to W3C's server in this case, I think.

**Comment by WesCossick** [comment]
Can we just catch the error instead and handle it more gracefully? I don't want to try to have to keep whatever value we pick in sync with whatever value they use.

**Comment by corymharper** [comment]
If there is a consistent way to identify that error we could... Will have to investigate.

**Comment by corymharper** [comment]
@WesCossick I can catch that it is a 400 error code, but the only message the servers give to accompany it is "Bad request." It seems like the most workable solution here is just more gracefully handle 400 error codes, but we can't do much about informing the developer about why they got a 400.
